// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PECCI_HRIS.Data;

#nullable disable

namespace PECCI_HRIS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260515062602_FixHolidaySeedData")]
    partial class FixHolidaySeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PECCI_HRIS.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceID"));

                    b.Property<DateTime?>("AdjustedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AdjustedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AttendanceStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan?>("BreakIn")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("BreakOut")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsManualEntry")
                        .HasColumnType("bit");

                    b.Property<double?>("LateMinutes")
                        .HasColumnType("float");

                    b.Property<double?>("OvertimeMinutes")
                        .HasColumnType("float");

                    b.Property<string>("Remarks")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<TimeSpan?>("TimeIn")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("TimeOut")
                        .HasColumnType("time");

                    b.Property<double?>("TotalHoursWorked")
                        .HasColumnType("float");

                    b.Property<double?>("UndertimeMinutes")
                        .HasColumnType("float");

                    b.HasKey("AttendanceID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValues")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OldValues")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuditID");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "HR",
                            DepartmentName = "Human Resources",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentID = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "FIN",
                            DepartmentName = "Finance & Accounting",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "IT",
                            DepartmentName = "Information Technology",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentID = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "OPS",
                            DepartmentName = "Operations",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentID = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "MKT",
                            DepartmentName = "Marketing",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("PECCI_HRIS.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CivilStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CompanyEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateHired")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRegularized")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSeparated")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PagIbigNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PersonalEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhilHealthNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PositionID")
                        .HasColumnType("int");

                    b.Property<string>("ProfilePicturePath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SSSNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Suffix")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TINNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("EmployeeNo")
                        .IsUnique();

                    b.HasIndex("PositionID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.EmployeeDeduction", b =>
                {
                    b.Property<int>("DeductionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeductionID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CutoffPeriod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DeductionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("DeductionID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("EmployeeDeductions");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.Holiday", b =>
                {
                    b.Property<int>("HolidayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HolidayID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HolidayType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("HolidayID");

                    b.HasIndex("HolidayDate", "HolidayType")
                        .IsUnique();

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            HolidayID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "New Year's Day",
                            HolidayType = "Regular",
                            IsRecurring = true,
                            Year = 2026
                        },
                        new
                        {
                            HolidayID = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayDate = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Maundy Thursday",
                            HolidayType = "Regular",
                            IsRecurring = false,
                            Year = 2026
                        },
                        new
                        {
                            HolidayID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayDate = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Good Friday",
                            HolidayType = "Regular",
                            IsRecurring = false,
                            Year = 2026
                        },
                        new
                        {
                            HolidayID = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayDate = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Araw ng Kagitingan (Day of Valor)",
                            HolidayType = "Regular",
                            IsRecurring = true,
                            Year = 2026
                        },
                        new
                        {
                            HolidayID = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Labor Day",
                            HolidayType = "Regular",
                            IsRecurring = true,
                            Year = 2026
                        },
                        new
                        {
                            HolidayID = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Independence Day",
                            HolidayType = "Regular",
                            IsRecurring = true,
                            Year = 2026
                        },
                        new
                        {
                            HolidayID = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayDate = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "National Heroes Day",
                            HolidayType = "Regular",
                            IsRecurring = false,
                            Remarks = "Last Monday of August",
                            Year = 2026
                        },
                        new
                        {
                            HolidayID = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayDate = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Bonifacio Day",
                            HolidayType = "Regular",
                            IsRecurring = true,
                            Year = 2026
                        },
                        new
                        {
                            HolidayID = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayDate = new DateTime(2026, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Christmas Day",
                            HolidayType = "Regular",
                            IsRecurring = true,
                            Year = 2026
                        },
                        new
                        {
                            HolidayID = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayDate = new DateTime(2026, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Rizal Day",
                            HolidayType = "Regular",
                            IsRecurring = true,
                            Year = 2026
                        },
                        new
                        {
                            HolidayID = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayDate = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Chinese New Year",
                            HolidayType = "Special",
                            IsRecurring = false,
                            Year = 2026
                        },
                        new
                        {
                            HolidayID = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayDate = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "EDSA People Power Revolution Anniversary",
                            HolidayType = "Special",
                            IsRecurring = true,
                            Year = 2026
                        },
                        new
                        {
                            HolidayID = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Black Saturday",
                            HolidayType = "Special",
                            IsRecurring = false,
                            Year = 2026
                        },
                        new
                        {
                            HolidayID = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayDate = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Ninoy Aquino Day",
                            HolidayType = "Special",
                            IsRecurring = true,
                            Year = 2026
                        },
                        new
                        {
                            HolidayID = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayDate = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "All Saints' Day",
                            HolidayType = "Special",
                            IsRecurring = true,
                            Year = 2026
                        },
                        new
                        {
                            HolidayID = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayDate = new DateTime(2026, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "All Souls' Day",
                            HolidayType = "Special",
                            IsRecurring = false,
                            Year = 2026
                        },
                        new
                        {
                            HolidayID = 17,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayDate = new DateTime(2026, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Feast of the Immaculate Conception",
                            HolidayType = "Special",
                            IsRecurring = true,
                            Year = 2026
                        },
                        new
                        {
                            HolidayID = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayDate = new DateTime(2026, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Christmas Eve",
                            HolidayType = "Special",
                            IsRecurring = false,
                            Year = 2026
                        },
                        new
                        {
                            HolidayID = 19,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "New Year's Eve",
                            HolidayType = "Special",
                            IsRecurring = false,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("PECCI_HRIS.Models.LeaveApplication", b =>
                {
                    b.Property<int>("LeaveApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveApplicationID"));

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HRApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HRApproverID")
                        .HasColumnType("int");

                    b.Property<string>("HRRemarks")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("LeaveTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ManagerApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ManagerApproverID")
                        .HasColumnType("int");

                    b.Property<string>("ManagerRemarks")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("NumberOfDays")
                        .HasColumnType("decimal(5,1)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("LeaveApplicationID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("LeaveTypeID");

                    b.ToTable("LeaveApplications");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.LeaveCredit", b =>
                {
                    b.Property<int>("LeaveCreditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveCreditID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("LeaveTypeID")
                        .HasColumnType("int");

                    b.Property<decimal>("PendingCredits")
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal>("TotalCredits")
                        .HasColumnType("decimal(5,1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UsedCredits")
                        .HasColumnType("decimal(5,1)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("LeaveCreditID");

                    b.HasIndex("LeaveTypeID");

                    b.HasIndex("EmployeeID", "LeaveTypeID", "Year")
                        .IsUnique();

                    b.ToTable("LeaveCredits");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.LeaveType", b =>
                {
                    b.Property<int>("LeaveTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveTypeID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefaultDaysPerYear")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("LeaveCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LeaveTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("bit");

                    b.HasKey("LeaveTypeID");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            LeaveTypeID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultDaysPerYear = 15,
                            IsActive = true,
                            IsPaid = true,
                            LeaveCode = "VL",
                            LeaveTypeName = "Vacation Leave",
                            RequiresApproval = true
                        },
                        new
                        {
                            LeaveTypeID = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultDaysPerYear = 15,
                            IsActive = true,
                            IsPaid = true,
                            LeaveCode = "SL",
                            LeaveTypeName = "Sick Leave",
                            RequiresApproval = true
                        },
                        new
                        {
                            LeaveTypeID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultDaysPerYear = 3,
                            IsActive = true,
                            IsPaid = true,
                            LeaveCode = "EL",
                            LeaveTypeName = "Emergency Leave",
                            RequiresApproval = true
                        },
                        new
                        {
                            LeaveTypeID = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultDaysPerYear = 105,
                            IsActive = true,
                            IsPaid = true,
                            LeaveCode = "ML",
                            LeaveTypeName = "Maternity Leave",
                            RequiresApproval = true
                        },
                        new
                        {
                            LeaveTypeID = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultDaysPerYear = 7,
                            IsActive = true,
                            IsPaid = true,
                            LeaveCode = "PL",
                            LeaveTypeName = "Paternity Leave",
                            RequiresApproval = true
                        });
                });

            modelBuilder.Entity("PECCI_HRIS.Models.PayrollRecord", b =>
                {
                    b.Property<int>("PayrollID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayrollID"));

                    b.Property<decimal>("Allowances")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DaysAbsent")
                        .HasColumnType("int");

                    b.Property<int>("DaysWorked")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HolidayPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LateDeductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LeaveDeductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NightDifferential")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherDeductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherEarnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OvertimePay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PagIbigContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PayPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhilHealthContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SSSContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("StoredGrossPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StoredNetPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StoredTotalDeductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("TotalLateMinutes")
                        .HasColumnType("float");

                    b.Property<double>("TotalOvertimeHours")
                        .HasColumnType("float");

                    b.Property<decimal>("UndertimeDeductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WithholdingTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WorkingDays")
                        .HasColumnType("int");

                    b.HasKey("PayrollID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("PayrollRecords");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.Position", b =>
                {
                    b.Property<int>("PositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionID"));

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PositionCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PositionTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PositionID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.RecurringDeductionSchedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleID"));

                    b.Property<decimal>("AmountPerCutoff")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AppliedInstallments")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CutoffPeriod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DeductionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TotalInstallments")
                        .HasColumnType("int");

                    b.HasKey("ScheduleID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("RecurringDeductionSchedules");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            Description = "Full system access",
                            IsActive = true,
                            RoleName = "HR Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            Description = "HR operations access",
                            IsActive = true,
                            RoleName = "HR Staff"
                        },
                        new
                        {
                            RoleID = 3,
                            Description = "Department management and approvals",
                            IsActive = true,
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleID = 4,
                            Description = "Self-service access",
                            IsActive = true,
                            RoleName = "Employee"
                        });
                });

            modelBuilder.Entity("PECCI_HRIS.Models.RolePermission", b =>
                {
                    b.Property<int>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionID"));

                    b.Property<bool>("CanCreate")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("CanView")
                        .HasColumnType("bit");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("PermissionID");

                    b.HasIndex("RoleID");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.SystemSetting", b =>
                {
                    b.Property<int>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingID"));

                    b.Property<string>("AllowedValues")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("bit");

                    b.Property<string>("SettingGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("SettingID");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            SettingID = 1,
                            DataType = "time",
                            Description = "Official work start time",
                            IsEditable = true,
                            SettingGroup = "Attendance",
                            SettingKey = "WorkStartTime",
                            SettingValue = "08:00",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 2,
                            DataType = "time",
                            Description = "Official work end time",
                            IsEditable = true,
                            SettingGroup = "Attendance",
                            SettingKey = "WorkEndTime",
                            SettingValue = "17:00",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 3,
                            DataType = "int",
                            Description = "Grace period in minutes (08:00 + 5 = 08:05 cutoff)",
                            IsEditable = true,
                            SettingGroup = "Attendance",
                            SettingKey = "GracePeriodMinutes",
                            SettingValue = "5",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 4,
                            DataType = "int",
                            Description = "Additional grace period in seconds",
                            IsEditable = true,
                            SettingGroup = "Attendance",
                            SettingKey = "GracePeriodSeconds",
                            SettingValue = "0",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 5,
                            DataType = "int",
                            Description = "Minimum overtime minutes before OT pay is credited",
                            IsEditable = true,
                            SettingGroup = "Attendance",
                            SettingKey = "OvertimeThresholdMinutes",
                            SettingValue = "30",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 6,
                            DataType = "time",
                            Description = "Lunch break start time",
                            IsEditable = true,
                            SettingGroup = "Attendance",
                            SettingKey = "LunchBreakStartTime",
                            SettingValue = "12:00",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 7,
                            DataType = "time",
                            Description = "Lunch break end time",
                            IsEditable = true,
                            SettingGroup = "Attendance",
                            SettingKey = "LunchBreakEndTime",
                            SettingValue = "13:00",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 8,
                            DataType = "int",
                            Description = "Lunch break duration in minutes",
                            IsEditable = true,
                            SettingGroup = "Attendance",
                            SettingKey = "LunchBreakDurationMinutes",
                            SettingValue = "60",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 9,
                            AllowedValues = "PerMinute,PerHour,FixedAmount,None",
                            DataType = "string",
                            Description = "How late deductions are computed",
                            IsEditable = true,
                            SettingGroup = "Attendance",
                            SettingKey = "LateDeductionType",
                            SettingValue = "PerMinute",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 10,
                            DataType = "decimal",
                            Description = "Fixed deduction per late minute (0 = auto from daily rate)",
                            IsEditable = true,
                            SettingGroup = "Attendance",
                            SettingKey = "LateDeductionAmountPerMinute",
                            SettingValue = "0",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 11,
                            AllowedValues = "PerMinute,PerHour,FixedAmount,None",
                            DataType = "string",
                            Description = "How undertime deductions are computed",
                            IsEditable = true,
                            SettingGroup = "Attendance",
                            SettingKey = "UndertimeDeductionType",
                            SettingValue = "PerMinute",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 12,
                            DataType = "decimal",
                            Description = "Fixed deduction per undertime minute (0 = auto)",
                            IsEditable = true,
                            SettingGroup = "Attendance",
                            SettingKey = "UndertimeDeductionAmountPerMinute",
                            SettingValue = "0",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 13,
                            DataType = "int",
                            Description = "Minutes before work start that time-in is allowed",
                            IsEditable = true,
                            SettingGroup = "Attendance",
                            SettingKey = "AllowTimeInBeforeMinutes",
                            SettingValue = "30",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 20,
                            DataType = "int",
                            Description = "First payroll cutoff day of the month",
                            IsEditable = true,
                            SettingGroup = "Payroll",
                            SettingKey = "CutoffDay1",
                            SettingValue = "15",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 21,
                            DataType = "int",
                            Description = "Second payroll cutoff day of the month",
                            IsEditable = true,
                            SettingGroup = "Payroll",
                            SettingKey = "CutoffDay2",
                            SettingValue = "30",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 22,
                            DataType = "decimal",
                            Description = "Regular overtime rate multiplier (DOLE: 1.25)",
                            IsEditable = true,
                            SettingGroup = "Payroll",
                            SettingKey = "OvertimeRateMultiplier",
                            SettingValue = "1.25",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 23,
                            DataType = "decimal",
                            Description = "Rest day overtime rate multiplier (DOLE: 1.30)",
                            IsEditable = true,
                            SettingGroup = "Payroll",
                            SettingKey = "RestDayOvertimeRateMultiplier",
                            SettingValue = "1.30",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 24,
                            DataType = "decimal",
                            Description = "Special non-working holiday rate multiplier",
                            IsEditable = true,
                            SettingGroup = "Payroll",
                            SettingKey = "SpecialHolidayRateMultiplier",
                            SettingValue = "1.30",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 25,
                            DataType = "decimal",
                            Description = "Regular holiday rate multiplier (DOLE: 2.00)",
                            IsEditable = true,
                            SettingGroup = "Payroll",
                            SettingKey = "RegularHolidayRateMultiplier",
                            SettingValue = "2.00",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 26,
                            DataType = "decimal",
                            Description = "Night differential rate (DOLE: 10% of hourly rate)",
                            IsEditable = true,
                            SettingGroup = "Payroll",
                            SettingKey = "NightDifferentialRate",
                            SettingValue = "0.10",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 27,
                            DataType = "time",
                            Description = "Night differential period start",
                            IsEditable = true,
                            SettingGroup = "Payroll",
                            SettingKey = "NightDifferentialStartTime",
                            SettingValue = "22:00",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 28,
                            DataType = "time",
                            Description = "Night differential period end",
                            IsEditable = true,
                            SettingGroup = "Payroll",
                            SettingKey = "NightDifferentialEndTime",
                            SettingValue = "06:00",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 30,
                            DataType = "decimal",
                            Description = "SSS employee contribution rate (4.5%)",
                            IsEditable = true,
                            SettingGroup = "Tax",
                            SettingKey = "SSSEmployeeRate",
                            SettingValue = "0.045",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 31,
                            DataType = "decimal",
                            Description = "PhilHealth employee share rate (2.5% of basic salary)",
                            IsEditable = true,
                            SettingGroup = "Tax",
                            SettingKey = "PhilHealthRate",
                            SettingValue = "0.025",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 32,
                            DataType = "decimal",
                            Description = "Pag-IBIG employee contribution rate (2%)",
                            IsEditable = true,
                            SettingGroup = "Tax",
                            SettingKey = "PagIbigRate",
                            SettingValue = "0.02",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 33,
                            DataType = "decimal",
                            Description = "Pag-IBIG maximum monthly employee contribution (₱100)",
                            IsEditable = true,
                            SettingGroup = "Tax",
                            SettingKey = "PagIbigMaxContribution",
                            SettingValue = "100.00",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SettingID = 34,
                            AllowedValues = "BIR_TRAIN_LAW_2023,BIR_TRAIN_LAW_2018",
                            DataType = "string",
                            Description = "BIR withholding tax table to use",
                            IsEditable = true,
                            SettingGroup = "Tax",
                            SettingKey = "TaxTableType",
                            SettingValue = "BIR_TRAIN_LAW_2023",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PECCI_HRIS.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeID")
                        .IsUnique()
                        .HasFilter("[EmployeeID] IS NOT NULL");

                    b.HasIndex("RoleID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.AttendanceRecord", b =>
                {
                    b.HasOne("PECCI_HRIS.Models.Employee", "Employee")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.Employee", b =>
                {
                    b.HasOne("PECCI_HRIS.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PECCI_HRIS.Models.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.EmployeeDeduction", b =>
                {
                    b.HasOne("PECCI_HRIS.Models.Employee", "Employee")
                        .WithMany("EmployeeDeductions")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.LeaveApplication", b =>
                {
                    b.HasOne("PECCI_HRIS.Models.Employee", "Employee")
                        .WithMany("LeaveApplications")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PECCI_HRIS.Models.LeaveType", "LeaveType")
                        .WithMany("LeaveApplications")
                        .HasForeignKey("LeaveTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.LeaveCredit", b =>
                {
                    b.HasOne("PECCI_HRIS.Models.Employee", "Employee")
                        .WithMany("LeaveCredits")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PECCI_HRIS.Models.LeaveType", "LeaveType")
                        .WithMany("LeaveCredits")
                        .HasForeignKey("LeaveTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.PayrollRecord", b =>
                {
                    b.HasOne("PECCI_HRIS.Models.Employee", "Employee")
                        .WithMany("PayrollRecords")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.Position", b =>
                {
                    b.HasOne("PECCI_HRIS.Models.Department", "Department")
                        .WithMany("Positions")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.RecurringDeductionSchedule", b =>
                {
                    b.HasOne("PECCI_HRIS.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.RolePermission", b =>
                {
                    b.HasOne("PECCI_HRIS.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.User", b =>
                {
                    b.HasOne("PECCI_HRIS.Models.Employee", "Employee")
                        .WithOne("UserAccount")
                        .HasForeignKey("PECCI_HRIS.Models.User", "EmployeeID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PECCI_HRIS.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.Employee", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("EmployeeDeductions");

                    b.Navigation("LeaveApplications");

                    b.Navigation("LeaveCredits");

                    b.Navigation("PayrollRecords");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.LeaveType", b =>
                {
                    b.Navigation("LeaveApplications");

                    b.Navigation("LeaveCredits");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("PECCI_HRIS.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
